### ISSUE TITLE
Провести проверку на большом файле

### ISSUE THREAD

**Issue by alexkoss** [Alf51/union-find#1]
Добрый день! Меня зовут Александр, сотрудник компании БалтИнфоКом.

Предлагаю осуществить проверку на большом файле.

Файл: https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-big.7z

В ответе должно быть количество групп и время выполнения.

**Comment by Alf51** [comment]
Доброго времени суток, Александр!
Осуществил проверку на большом файле.
Количество групп с более чем одним  элементом 111547
Время выполнения 10 секунд (Ryzen 5500U)

**Comment by alexkoss** [comment]
Ответ некорректный. Попробуете ещё раз?

**Comment by alexkoss** [comment]
@Alf51 Спасибо за уделённое время.
